#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          autoraise      \
    window_origin_display        default        \
    window_placement             second_child   \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    external_bar                 all:38:0       \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   1              \
    layout                       bsp            \
    mouse_modifier               ctrl           \
    mouse_action1                resize         \
    mouse_action2                move           \
    mouse_drop_action            swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on
yabai -m rule --add app="^ColorSlurp$" manage=off sticky=on
yabai -m rule --add app="^eqMac$" manage=off sticky=on

echo "yabai configuration loaded.."

