tap "crisidev/homebrew-chunkwm"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "ack"
brew "openssl"
brew "composer"
brew "coreutils"
brew "curl"
brew "ffmpeg"
brew "figlet"
brew "fzf"
brew "gist"
brew "git"
brew "htop"
brew "hub"
brew "jq"
brew "links"
brew "mame"
brew "mariadb", restart_service: true
brew "mosh"
brew "mpc"
brew "mpv"
brew "ncmpcpp"
brew "neofetch"
brew "neovim"
brew "nginx"
brew "ngrep"
brew "nmap"
brew "nvm"
brew "php@7.1"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ranger"
brew "ssh-copy-id"
brew "tcpdump"
brew "tmux"
brew "tree"
brew "unrar"
brew "unzip"
brew "vim"
brew "weechat", args: ["with-curl", "with-lua", "with-perl", "with-python@2", "with-ruby"]
brew "wget"
brew "yarn"
brew "z"
brew "zip"
brew "zplug"
brew "zsh"
brew "chunkwm", args: ["HEAD"]
brew "skhd"

cask "adobe-air"
cask "caprine"
cask "day-o"
cask "discord"
cask "dropbox"
cask "enpass"
cask "firefox"
cask "flume"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hipchat"
cask "iterm2-nightly"
cask "lastfm"
cask "processing"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicksilver"
cask "scratch"
cask "sequel-pro"
cask "signal"
cask "skype"
cask "spotify"
cask "spotmenu"
cask "sonos"
cask "steam"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "transmit"
cask "twitch"
cask "virtualbox"
cask "vlc"
cask "whatsapp"
cask "wireshark"

mas "Airmail 3", id: 918858936
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "QuickNFO", id: 412843352
mas "Twitter", id: 409789998
mas "Xcode", id: 497799835

