# General
export ZSH_HOME=$HOME/.zsh
export PROJECTS=$HOME/Development

# Xcode
# @NOTE Maybe theres a better way to set devtools paths?
export PATH="/Applications/Xcode.app/Contents/Developer/usr/bin/:$PATH"

# Android
export ANDROID_HOME="/opt/homebrew/Caskroom/android-platform-tools/35.0.2/"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

# Gameboy
export SDCCDIR="$PROJECTS/gameboy/sdcc"
export GBDK="$PROJECTS/gameboy/gbdk-2020/build/gbdk"
export PATH=$GBDK/bin:$SDCCDIR/bin:$PATH

# Amiga
export VBCC="$PROJECTS/amiga/amiga-cc/vbcc/"
export PATH=$VBCC/bin:$PATH

# Go
export GOPATH="$PROJECTS/go"
export PATH=$GOPATH/bin:$PATH

# Java
export SPRING_PROFILES_ACTIVE=local
export OPERATOR=pip-dk

# Python
export PYTHONDONTWRITEBYTECODE=True

# Rust
export CARGO_HOME="$HOME/.cargo"
export PATH=$CARGO_HOME/bin:$PATH

# Git
export GITHUB_ACTOR=$GITHUB_ACTOR
export GITHUB_TOKEN=$GITHUB_TOKEN

# Ruby
export PATH="$PATH:$HOME/.rvm/bin"

# Editor
export EDITOR=nvim #BTW
export VISUAL=$EDITOR

# asdf
export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# Completions
fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
fpath=(/Users/christian/.docker/completions $fpath)
autoload -Uz compinit && compinit

# FZF
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Lang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Load all functions in fn dir
for config_file ($ZSH_HOME/**/*.zsh) source $config_file
# for config_file ($ZSH_HOME/**/completion.sh) source $config_file

# Paths
export PATH="$(asdf-paths):$HOME/.bin:$HOME/.local/bin:$PATH"

# Mac specifics
if [[ "$(uname -s)" == "Darwin" ]] then;
  # Mac SDKs
  export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)

  # Homebrew
  export HOMEBREW_NO_ENV_HINTS=1
  eval "$(/opt/homebrew/bin/brew shellenv)"
  # eval "$(/usr/local/bin/brew shellenv)"
fi

# Zplug
[ -z "$ZPLUG_HOME" ] && export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug 'rupa/z', use:'*.sh'
zplug 'junegunn/fzf', \
    use:"shell", \
    hook-build:'./install --all --no-update-rc --no-key-bindings'

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

# sdkman
export SDKMAN_DIR="/Users/christian/.sdkman"
[[ -s "/Users/christian/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/christian/.sdkman/bin/sdkman-init.sh"

