return {}
-- return {
-- 	"goolord/alpha-nvim",
-- 	config = function()
-- 		require("alpha").setup(require("alpha.themes.dashboard").config)
-- 	end,
-- }

-- return {
-- 	"nvimdev/dashboard-nvim",
-- 	enabled = false,
-- 	event = "VimEnter",
-- 	config = function()
-- 		require("dashboard").setup({
-- 			theme = "hyper",
-- 			config = {
-- 				week_header = {
-- 					enable = true,
-- 				},
-- 				shortcut = {
-- 					{ desc = "󰊳 Update", group = "@property", action = "Lazy update", key = "u" },
-- 				},
-- 			},
-- 		})
-- 	end,
-- 	dependencies = { { "nvim-tree/nvim-web-devicons" } },
-- }
